DROP TABLE IF EXISTS RECIPE;

CREATE TABLE RECIPE(
    RECIPE_ID LONG AUTO_INCREMENT PRIMARY KEY,
    RECIPE_TITLE VARCHAR(250) NOT NULL,
    MEAL_TYPE VARCHAR(250) NOT NULL,
    NUMBER_IT_SERVES INTEGER NOT NULL,
    DIFFICULTY_LEVEL VARCHAR(250) NOT NULL);

DROP TABLE IF EXISTS INGREDIENT;

CREATE TABLE INGREDIENT(
    INGREDIENT_ID LONG AUTO_INCREMENT PRIMARY KEY,
    INGREDIENT_NAME VARCHAR(250) NOT NULL,
    RECIPE_ID LONG REFERENCES RECIPE(RECIPE_ID)
);
